### ISSUE TITLE
ruby-latest points to 1.0.971225

### ISSUE THREAD

**Issue by yourpalal** [krautcomputing/rubydocs#10]
Instead of pointing to the docs for the most advanced copy of ruby, https://rubydocs.org/d/ruby-latest points to docs for 1.0.971225 looks like that version of ruby was released [Thu Dec 25 17:06:30 1997](https://github.com/k0kubun/ruby-prehistory/commit/4207990990f8c8da414710816c32ae5fd0ae6987) so it's definitely not new!

I'm thinking something triggered these docs to get re-indexed and that caused them to be marked as the "latest" version of ruby.

PS. thanks for continuing to run this awesome service!

**Comment by manuelmeurer** [comment]
Whoops, seems like there were a few Ruby "releases" 6 days ago: https://github.com/ruby/ruby/releases
Probably old tags that haven't been pushed before.

I'll set the latest version manually to 2.6.3 and with the next release it should start working as expected again.

P.S.: Glad you like RubyDocs! I have no idea how many people use it, since all the docs are served straight from a CDN with no tracking, so it's always great to hear from users directly. :)
